"""Repository and unit-of-work interfaces used by the service layer.

Services depend only on these protocols; concrete implementations live in
``billing_engine.adapters.db``.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from billing_engine.domain.entities import (
    AuditLog,
    CommissionRule,
    CreditEntry,
    Customer,
    EntitlementOverride,
    Event,
    Feature,
    Invoice,
    InvoiceLine,
    License,
    LicenseAllocation,
    Partner,
    PartnerAccount,
    PartnerAgreement,
    PartnerInvoice,
    PartnerInvoiceLine,
    PartnerLedgerEntry,
    PartnerPayment,
    PartnerPayout,
    PartnerPayoutLine,
    PartnerStatement,
    Payment,
    Plan,
    PlanEntitlement,
    PlanVersion,
    Price,
    Product,
    Subscription,
    SubscriptionAdjustment,
)


class CustomerRepository(Protocol):
    def add(self, customer: Customer) -> None: ...

    def get(self, customer_id: str) -> Customer | None: ...

    def get_by_external_id(self, external_id: str) -> Customer | None: ...

    def update(self, customer: Customer) -> None: ...

    def list(self, limit: int = 100, offset: int = 0) -> list[Customer]: ...


class CatalogRepository(Protocol):
    def add_product(self, product: Product) -> None: ...

    def get_product(self, product_id: str) -> Product | None: ...

    def add_plan(self, plan: Plan) -> None: ...

    def get_plan(self, plan_id: str) -> Plan | None: ...

    def get_plan_for_update(self, plan_id: str) -> Plan | None: ...

    def get_plan_by_key(self, key: str) -> Plan | None: ...

    def update_plan(self, plan: Plan) -> None: ...

    def list_plans(self, limit: int = 100, offset: int = 0) -> list[Plan]: ...

    def add_plan_version(self, version: PlanVersion) -> None: ...

    def get_plan_version(self, version_id: str) -> PlanVersion | None: ...

    def list_plan_versions(self, plan_id: str) -> list[PlanVersion]: ...

    def add_price(self, price: Price) -> None: ...

    def get_price(self, price_id: str) -> Price | None: ...

    def list_prices(self, plan_version_id: str) -> list[Price]: ...

    def add_feature(self, feature: Feature) -> None: ...

    def get_feature(self, feature_id: str) -> Feature | None: ...

    def get_feature_by_key(self, key: str) -> Feature | None: ...

    def list_features(self) -> list[Feature]: ...

    def add_plan_entitlement(self, entitlement: PlanEntitlement) -> None: ...

    def list_plan_entitlements(self, plan_version_id: str) -> list[PlanEntitlement]: ...

    def clear_plan_entitlements(self, plan_version_id: str) -> None: ...


class SubscriptionRepository(Protocol):
    def add(self, subscription: Subscription) -> None: ...

    def get(self, subscription_id: str) -> Subscription | None: ...

    def update(self, subscription: Subscription) -> None: ...

    def list_for_customer(self, customer_id: str) -> list[Subscription]: ...

    def list_due(self, before: datetime) -> list[Subscription]: ...

    def add_adjustment(self, adjustment: SubscriptionAdjustment) -> None: ...

    def list_adjustments(self, subscription_id: str) -> list[SubscriptionAdjustment]: ...


class EntitlementRepository(Protocol):
    def add_override(self, override: EntitlementOverride) -> None: ...

    def get_override(self, override_id: str) -> EntitlementOverride | None: ...

    def get_customer_override(
        self, customer_id: str, feature_id: str
    ) -> EntitlementOverride | None: ...

    def get_subscription_override(
        self, subscription_id: str, feature_id: str
    ) -> EntitlementOverride | None: ...

    def list_for_customer(self, customer_id: str) -> list[EntitlementOverride]: ...

    def list_for_subscription(self, subscription_id: str) -> list[EntitlementOverride]: ...

    def delete_override(self, override_id: str) -> None: ...


class InvoiceRepository(Protocol):
    def add_invoice(self, invoice: Invoice) -> None: ...

    def get_invoice(self, invoice_id: str) -> Invoice | None: ...

    def update_invoice(self, invoice: Invoice) -> None: ...

    def list_invoices(self, customer_id: str) -> list[Invoice]: ...

    def add_line(self, line: InvoiceLine) -> None: ...

    def list_lines(self, invoice_id: str) -> list[InvoiceLine]: ...

    def add_payment(self, payment: Payment) -> None: ...

    def list_payments(self, invoice_id: str) -> list[Payment]: ...


class CreditRepository(Protocol):
    def add_entry(self, entry: CreditEntry) -> None: ...

    def list_entries(self, customer_id: str) -> list[CreditEntry]: ...

    def balance(self, customer_id: str, currency: str) -> int: ...

    def balance_for_update(self, customer_id: str, currency: str) -> int: ...


class AuditRepository(Protocol):
    def add(self, entry: AuditLog) -> None: ...

    def list(
        self,
        entity_type: str | None = None,
        entity_id: str | None = None,
        action: str | None = None,
        actor_id: str | None = None,
        since: datetime | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[AuditLog]: ...


class EventRepository(Protocol):
    def add(self, event: Event) -> None: ...

    def list_pending(self, now: datetime, limit: int = 100) -> list[Event]: ...

    def mark_delivered(self, event_id: str, delivered_at: datetime) -> None: ...

    def mark_failed(
        self, event_id: str, error: str, retry_at: datetime, *, final: bool = False
    ) -> None: ...


class ReportRepository(Protocol):
    def overview(self, currency: str) -> dict[str, Any]: ...

    def subscription_counts(self) -> dict[str, int]: ...

    def revenue_by_plan(self, currency: str) -> list[dict[str, Any]]: ...

    def outstanding_invoices(self) -> dict[str, Any]: ...

    def feature_adoption(self) -> list[dict[str, Any]]: ...

    def channel_revenue(self, currency: str) -> list[dict[str, Any]]: ...


class PartnerRepository(Protocol):
    def add_partner(self, partner: Partner) -> None: ...

    def get_partner(self, partner_id: str) -> Partner | None: ...

    def get_partner_by_external_id(self, external_id: str) -> Partner | None: ...

    def update_partner(self, partner: Partner) -> None: ...

    def list_partners(self, limit: int = 100, offset: int = 0) -> list[Partner]: ...

    def add_agreement(self, agreement: PartnerAgreement) -> None: ...

    def get_agreement(self, agreement_id: str) -> PartnerAgreement | None: ...

    def list_agreements(self, partner_id: str) -> list[PartnerAgreement]: ...

    def add_commission_rule(self, rule: CommissionRule) -> None: ...

    def get_commission_rule(self, rule_id: str) -> CommissionRule | None: ...

    def list_commission_rules(self) -> list[CommissionRule]: ...


class LicenseRepository(Protocol):
    def add_allocation(self, allocation: LicenseAllocation) -> None: ...

    def get_allocation(self, allocation_id: str) -> LicenseAllocation | None: ...

    def get_allocation_for_update(self, allocation_id: str) -> LicenseAllocation | None: ...

    def update_allocation(self, allocation: LicenseAllocation) -> None: ...

    def list_allocations(self, partner_id: str) -> list[LicenseAllocation]: ...

    def add_license(self, license_: License) -> None: ...

    def get_license(self, license_id: str) -> License | None: ...

    def update_license(self, license_: License) -> None: ...

    def list_licenses(self, partner_id: str) -> list[License]: ...

    def list_licenses_for_allocation(self, allocation_id: str) -> list[License]: ...


class PartnerAccountRepository(Protocol):
    def get_account(
        self, partner_id: str, currency: str, account_type: str
    ) -> PartnerAccount | None: ...

    def list_accounts(self, partner_id: str) -> list[PartnerAccount]: ...

    def add_account(self, account: PartnerAccount) -> None: ...

    def update_account(self, account: PartnerAccount) -> None: ...

    def add_entry(self, entry: PartnerLedgerEntry) -> None: ...

    def list_entries(
        self,
        partner_id: str,
        currency: str | None = None,
        since: datetime | None = None,
        until: datetime | None = None,
    ) -> list[PartnerLedgerEntry]: ...

    def add_invoice(self, invoice: PartnerInvoice) -> None: ...

    def get_invoice(self, invoice_id: str) -> PartnerInvoice | None: ...

    def update_invoice(self, invoice: PartnerInvoice) -> None: ...

    def list_invoices(self, partner_id: str) -> list[PartnerInvoice]: ...

    def add_invoice_line(self, line: PartnerInvoiceLine) -> None: ...

    def list_invoice_lines(self, invoice_id: str) -> list[PartnerInvoiceLine]: ...

    def add_payment(self, payment: PartnerPayment) -> None: ...

    def list_payments(self, partner_id: str) -> list[PartnerPayment]: ...

    def add_payout(self, payout: PartnerPayout) -> None: ...

    def get_payout(self, payout_id: str) -> PartnerPayout | None: ...

    def update_payout(self, payout: PartnerPayout) -> None: ...

    def add_payout_line(self, line: PartnerPayoutLine) -> None: ...

    def list_payout_lines(self, payout_id: str) -> list[PartnerPayoutLine]: ...

    def add_statement(self, statement: PartnerStatement) -> None: ...

    def list_statements(self, partner_id: str) -> list[PartnerStatement]: ...


class Repositories(Protocol):
    """Unit of work exposing repositories and transaction control."""

    customers: CustomerRepository
    catalog: CatalogRepository
    subscriptions: SubscriptionRepository
    entitlements: EntitlementRepository
    invoices: InvoiceRepository
    credits: CreditRepository
    audit: AuditRepository
    events: EventRepository
    reports: ReportRepository
    partners: PartnerRepository
    licenses: LicenseRepository
    partner_accounts: PartnerAccountRepository

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def flush(self) -> None: ...
